### ISSUE TITLE
Catch error and inform user when failing to connect to proxy

### ISSUE THREAD

**Issue by nworbneb** [Alexqw/xbmc-gamepass#226]
My proxy server was down and trying to load gamepass gave a fatal error:

14:10:13 T:140557153994496  NOTICE: [plugin.video.nfl.gamepass-0.9.0]: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 568, in <module>
                                                gpr.login(username, password)
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 350, in login
                                                if self.check_for_subscription():
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 150, in check_for_subscription
                                                sc_data = self.make_request(url=url, method='post', payload=post_data)
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 392, in make_request
                                                self.log('Error: - %s' % error.value)
                                            AttributeError: 'ConnectionError' object has no attribute 'value'

**Comment by Alexqw** [comment]
@nworbneb Good point. We should catch this error and provide a more helpful message for the user.

---Alex
